### ISSUE TITLE
Letter complete experience.

### ISSUE THREAD

**Issue by steveruizok** [steveruizok/kdtype#3]
Play a sound when the user presses the correct letter.

**Comment by sifferhans** [comment]
@steveruizok Are you working on this? If not, I can give it a try :)

**Comment by steveruizok** [comment]
Go for it! 

My only notes would be NOT to play a sound when the wrong key is pressed; we have a different game where that's the case and it's the most annoying thing in the world lol

**Comment by sifferhans** [comment]
Haha yeah, that sounds about right
Is there an idea to animate the current letter as well? I dont know how whimsical the game is supposed to be, but a slight bounce or something feels like it would fit quite well!

**Comment by steveruizok** [comment]
Whenever my kid finishes a word she does the same left and right dance as the word's complete animation. 😂 Maybe we could have a bunch of animations and pick one at random?

**Comment by sifferhans** [comment]
This was fixed in #9 😊
