### ISSUE TITLE
Add Sounds

### ISSUE THREAD

**Issue by ermincelikovic** [steveruizok/kdtype#7]
I would imagine that adding sounds for right letter, wrong letter and correctly guessed word (something like TA-DA) would stimulate kids even more! :)

**Comment by ermincelikovic** [comment]
Took a couple of minutes to find MVP sounds:
Correct letter: https://freesound.org/people/Eponn/sounds/531510/
Wrong letter: https://freesound.org/people/Beetlemuse/sounds/587253/
TA-DA: https://freesound.org/people/nolhananas/sounds/476340/

**Comment by jhsu** [comment]
I just made a pull-request to add audio for letters as they are pressed so the groundwork is ready!

https://github.com/steveruizok/kdtype/pull/8

**Comment by steveruizok** [comment]
Sounds good! Its in now.
